apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-ingestion-service
  namespace: axion-app
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1


  selector:
    matchLabels:
      app: axion-ingestion-service

  template:
    metadata:
      labels:
        app: axion-ingestion-service

    spec:
      containers:
      - name: axion-ingestion-service
        image: acrtodoappjay.azurecr.io/axion-ingestion-service:v2
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: secrets-store-ingestion
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
        - name: API--URL
          valueFrom:
            secretKeyRef:
              name: azure-secret
              key: api-url
      volumes:
      - name: secrets-store-ingestion
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kv"