apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv
  namespace: axion-app
spec:
  provider: azure

  secretObjects:
  - secretName: azure-secret
    type: Opaque
    data:
    - objectName: DATABASE--URL
      key: db-url

    - objectName: API--URL
      key: api-url

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"

    # AKS Key Vault Add-on Client ID
    userAssignedIdentityID: "418c3d7a-0f39-4dc9-b478-0449adb26698"

    keyvaultName: "jaydeep-key-vault3"
    tenantId: "44bda376-d606-4e95-8c78-2e854c2f6079"

    objects: |
      array:
        - |
          objectName: DATABASE--URL
          objectType: secret
        - |
          objectName: API--URL
          objectType: secret